name: CI with Cache

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache-demo
          key: cache-b96f2b9

      - name: prime-cache-b96f2b9
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ]; then
            echo "Cache Hit"
          else
            echo "Cache Miss"
            mkdir -p ~/.cache-demo
            echo "priming cache" > ~/.cache-demo/data.txt
          fi
